# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies on backend
      run: dotnet restore /workspaces/dotnet-codespaces/SampleApp/BackEnd
    - name: Restore dependencies on frontend
      run: dotnet restore /workspaces/dotnet-codespaces/SampleApp/FrontEnd
    - name: Build
      run: dotnet build --no-restore

# Comment added to Test step as the project doesn't contain a test project
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
